version: '3.8'

services:
  consul:
    image: library/consul:1.15.4
    ports:
      - "8500:8500"  # Consul UI
    volumes:
      - ./consul/config:/consul/config
    command: agent -dev -client 0.0.0.0
    networks:
      - app-network

  gateway:
    build: express-gateway
    ports:
      - "8081:8081" # Exposed port for http
      - "9876:9876" # Exposed port for admin
    depends_on:
      - ussd-service
      - payment-service
      - notification-service
      - ticket-service
      - consul
    networks:
      - app-network

  ussd-service:
    build: ussd-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  payment-service:
    build: payment-service
    ports:
      - "4001:4001"
    networks:
      - app-network


  notification-service:
    build: notification-service
    ports:
      - "5005:5005"
    networks:
      - app-network

  ticket-service:
    build: ticket-service
    ports:
      - "6001:6001"
    networks:
      - app-network
    depends_on:
      - consul


networks:
  app-network:
    driver: bridge