name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'express-gateway/**'
      - 'ussd-service/**'
      - 'payment-service/**'
      - 'notification-service/**'
      - 'ticket-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [express-gateway, ussd-service, payment-service, notification-service, ticket-service]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: freddy008/${{ matrix.service }}:latest
          no-cache: true